import type { InstrumentSeed, NewsDTO, VideoDTO } from "./types";

function inst(
  partial: InstrumentSeed & { basePrice: number },
): InstrumentSeed {
  return {
    featured: false,
    sortOrder: 100,
    marketCap: undefined,
    peRatio: undefined,
    dividendYield: undefined,
    week52High: partial.basePrice * 1.28,
    week52Low: partial.basePrice * 0.72,
    avgVolume: undefined,
    ...partial,
  };
}

export const INSTRUMENT_CATALOG: InstrumentSeed[] = [
  inst({
    id: "XU100",
    symbol: "XU100",
    yahooSymbol: "XU100.IS",
    name: "BIST 100",
    nameTr: "BIST 100",
    type: "index",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Endeks",
    description: "Benchmark index of Borsa Istanbul covering the 100 most traded companies.",
    descriptionTr: "Borsa İstanbul'un en çok işlem gören 100 şirketini kapsayan gösterge endeksi.",
    basePrice: 9842,
    featured: true,
    sortOrder: 1,
    avgVolume: 18_400_000_000,
  }),
  inst({
    id: "XU030",
    symbol: "XU030",
    yahooSymbol: "XU030.IS",
    name: "BIST 30",
    nameTr: "BIST 30",
    type: "index",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Endeks",
    description: "Blue-chip index of the 30 largest Borsa Istanbul listings.",
    descriptionTr: "Borsa İstanbul'un en büyük 30 şirketini izleyen mavi çip endeksi.",
    basePrice: 10890,
    featured: true,
    sortOrder: 2,
    avgVolume: 9_200_000_000,
  }),
  inst({
    id: "SPX",
    symbol: "S&P 500",
    yahooSymbol: "^GSPC",
    name: "S&P 500",
    nameTr: "S&P 500",
    type: "index",
    region: "us",
    exchange: "SNP",
    currency: "USD",
    sector: "Endeks",
    description: "Market-cap weighted index of 500 large U.S. companies.",
    descriptionTr: "ABD'nin 500 büyük şirketini kapsayan piyasa değerine dayalı endeks.",
    basePrice: 5648.4,
    featured: true,
    sortOrder: 3,
    avgVolume: 3_800_000_000,
  }),
  inst({
    id: "DJI",
    symbol: "DJI",
    yahooSymbol: "^DJI",
    name: "Dow Jones",
    nameTr: "Dow Jones",
    type: "index",
    region: "us",
    exchange: "DJI",
    currency: "USD",
    sector: "Endeks",
    description: "Price-weighted index of 30 large U.S. industrials.",
    descriptionTr: "30 büyük ABD sanayi şirketini izleyen fiyat ağırlıklı endeks.",
    basePrice: 41520,
    featured: true,
    sortOrder: 4,
  }),
  inst({
    id: "IXIC",
    symbol: "NASDAQ",
    yahooSymbol: "^IXIC",
    name: "Nasdaq Composite",
    nameTr: "Nasdaq Bileşik",
    type: "index",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Endeks",
    description: "Broad index of Nasdaq-listed companies, heavy in technology.",
    descriptionTr: "Nasdaq'ta işlem gören şirketlerin geniş endeksi; teknoloji ağırlıklıdır.",
    basePrice: 17842,
    featured: true,
    sortOrder: 5,
  }),
  inst({
    id: "RUT",
    symbol: "RUT",
    yahooSymbol: "^RUT",
    name: "Russell 2000",
    nameTr: "Russell 2000",
    type: "index",
    region: "us",
    exchange: "RUSSELL",
    currency: "USD",
    sector: "Endeks",
    description: "U.S. small-cap benchmark.",
    descriptionTr: "ABD küçük ölçekli şirketler gösterge endeksi.",
    basePrice: 2214,
    sortOrder: 6,
  }),
  inst({
    id: "VIX",
    symbol: "VIX",
    yahooSymbol: "^VIX",
    name: "CBOE Volatility",
    nameTr: "VIX Oynaklık",
    type: "index",
    region: "us",
    exchange: "CBOE",
    currency: "USD",
    sector: "Oynaklık",
    description: "Implied volatility gauge for the S&P 500.",
    descriptionTr: "S&P 500 için ima edilen oynaklık göstergesi.",
    basePrice: 16.4,
    sortOrder: 7,
  }),
  inst({
    id: "FTSE",
    symbol: "FTSE",
    yahooSymbol: "^FTSE",
    name: "FTSE 100",
    nameTr: "FTSE 100",
    type: "index",
    region: "eu",
    exchange: "LSE",
    currency: "GBP",
    sector: "Endeks",
    description: "100 largest companies listed on the London Stock Exchange.",
    descriptionTr: "Londra Borsası'nın en büyük 100 şirketi.",
    basePrice: 8284,
    featured: true,
    sortOrder: 8,
  }),
  inst({
    id: "DAX",
    symbol: "DAX",
    yahooSymbol: "^GDAXI",
    name: "DAX",
    nameTr: "DAX",
    type: "index",
    region: "eu",
    exchange: "XETRA",
    currency: "EUR",
    sector: "Endeks",
    description: "40 blue-chip German companies.",
    descriptionTr: "Almanya'nın 40 mavi çip şirketini kapsayan endeks.",
    basePrice: 18740,
    featured: true,
    sortOrder: 9,
  }),
  inst({
    id: "N225",
    symbol: "Nikkei",
    yahooSymbol: "^N225",
    name: "Nikkei 225",
    nameTr: "Nikkei 225",
    type: "index",
    region: "asia",
    exchange: "JPX",
    currency: "JPY",
    sector: "Endeks",
    description: "Price-weighted index of 225 Tokyo-listed companies.",
    descriptionTr: "Tokyo'da işlem gören 225 şirketin fiyat ağırlıklı endeksi.",
    basePrice: 39120,
    featured: true,
    sortOrder: 10,
  }),
  inst({
    id: "HSI",
    symbol: "HSI",
    yahooSymbol: "^HSI",
    name: "Hang Seng",
    nameTr: "Hang Seng",
    type: "index",
    region: "asia",
    exchange: "HKEX",
    currency: "HKD",
    sector: "Endeks",
    description: "Hong Kong benchmark index.",
    descriptionTr: "Hong Kong gösterge endeksi.",
    basePrice: 17890,
    sortOrder: 11,
  }),
  inst({
    id: "AAPL",
    symbol: "AAPL",
    yahooSymbol: "AAPL",
    name: "Apple",
    nameTr: "Apple",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Teknoloji",
    description: "Consumer electronics, services and wearables.",
    descriptionTr: "Tüketici elektroniği, hizmetler ve giyilebilir cihazlar.",
    basePrice: 226.4,
    marketCap: 3.42e12,
    peRatio: 34.2,
    dividendYield: 0.44,
    featured: true,
    sortOrder: 20,
    avgVolume: 52_000_000,
  }),
  inst({
    id: "MSFT",
    symbol: "MSFT",
    yahooSymbol: "MSFT",
    name: "Microsoft",
    nameTr: "Microsoft",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Teknoloji",
    description: "Cloud, productivity software and AI platforms.",
    descriptionTr: "Bulut, üretkenlik yazılımları ve yapay zeka platformları.",
    basePrice: 428.9,
    marketCap: 3.19e12,
    peRatio: 36.8,
    dividendYield: 0.72,
    featured: true,
    sortOrder: 21,
    avgVolume: 22_000_000,
  }),
  inst({
    id: "NVDA",
    symbol: "NVDA",
    yahooSymbol: "NVDA",
    name: "NVIDIA",
    nameTr: "NVIDIA",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Teknoloji",
    description: "Graphics processors and accelerated computing.",
    descriptionTr: "Grafik işlemciler ve hızlandırılmış hesaplama.",
    basePrice: 118.6,
    marketCap: 2.91e12,
    peRatio: 52.4,
    featured: true,
    sortOrder: 22,
    avgVolume: 280_000_000,
  }),
  inst({
    id: "GOOGL",
    symbol: "GOOGL",
    yahooSymbol: "GOOGL",
    name: "Alphabet",
    nameTr: "Alphabet",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "İletişim",
    description: "Search, advertising, cloud and autonomous systems.",
    descriptionTr: "Arama, reklam, bulut ve otonom sistemler.",
    basePrice: 172.3,
    marketCap: 2.11e12,
    peRatio: 24.1,
    sortOrder: 23,
    avgVolume: 24_000_000,
  }),
  inst({
    id: "AMZN",
    symbol: "AMZN",
    yahooSymbol: "AMZN",
    name: "Amazon",
    nameTr: "Amazon",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Tüketici",
    description: "E-commerce, logistics and cloud infrastructure.",
    descriptionTr: "E-ticaret, lojistik ve bulut altyapısı.",
    basePrice: 196.8,
    marketCap: 2.06e12,
    peRatio: 41.5,
    sortOrder: 24,
    avgVolume: 38_000_000,
  }),
  inst({
    id: "META",
    symbol: "META",
    yahooSymbol: "META",
    name: "Meta Platforms",
    nameTr: "Meta",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "İletişim",
    description: "Social platforms and reality labs.",
    descriptionTr: "Sosyal platformlar ve gerçeklik laboratuvarları.",
    basePrice: 548.2,
    marketCap: 1.39e12,
    peRatio: 26.7,
    sortOrder: 25,
    avgVolume: 14_000_000,
  }),
  inst({
    id: "TSLA",
    symbol: "TSLA",
    yahooSymbol: "TSLA",
    name: "Tesla",
    nameTr: "Tesla",
    type: "stock",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "Otomotiv",
    description: "Electric vehicles and energy storage.",
    descriptionTr: "Elektrikli araçlar ve enerji depolama.",
    basePrice: 248.5,
    marketCap: 7.95e11,
    peRatio: 68.4,
    sortOrder: 26,
    avgVolume: 92_000_000,
  }),
  inst({
    id: "JPM",
    symbol: "JPM",
    yahooSymbol: "JPM",
    name: "JPMorgan Chase",
    nameTr: "JPMorgan",
    type: "stock",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    sector: "Finans",
    description: "Global investment and commercial bank.",
    descriptionTr: "Küresel yatırım ve ticari bankacılık.",
    basePrice: 214.7,
    marketCap: 6.1e11,
    peRatio: 12.4,
    dividendYield: 2.2,
    sortOrder: 27,
    avgVolume: 8_400_000,
  }),
  inst({
    id: "V",
    symbol: "V",
    yahooSymbol: "V",
    name: "Visa",
    nameTr: "Visa",
    type: "stock",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    sector: "Finans",
    description: "Global electronic payments network.",
    descriptionTr: "Küresel elektronik ödeme ağı.",
    basePrice: 312.4,
    marketCap: 6.05e11,
    peRatio: 31.2,
    dividendYield: 0.74,
    sortOrder: 28,
  }),
  inst({
    id: "UNH",
    symbol: "UNH",
    yahooSymbol: "UNH",
    name: "UnitedHealth",
    nameTr: "UnitedHealth",
    type: "stock",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    sector: "Sağlık",
    description: "Health insurance and care services.",
    descriptionTr: "Sağlık sigortası ve bakım hizmetleri.",
    basePrice: 568.1,
    marketCap: 5.22e11,
    peRatio: 21.8,
    dividendYield: 1.5,
    sortOrder: 29,
  }),
  inst({
    id: "XOM",
    symbol: "XOM",
    yahooSymbol: "XOM",
    name: "Exxon Mobil",
    nameTr: "Exxon Mobil",
    type: "stock",
    region: "us",
    exchange: "NYSE",
    currency: "USD",
    sector: "Enerji",
    description: "Integrated oil and gas producer.",
    descriptionTr: "Entegre petrol ve doğal gaz üreticisi.",
    basePrice: 118.3,
    marketCap: 5.05e11,
    peRatio: 14.6,
    dividendYield: 3.4,
    sortOrder: 30,
  }),
  inst({
    id: "THYAO",
    symbol: "THYAO",
    yahooSymbol: "THYAO.IS",
    name: "Türk Hava Yolları",
    nameTr: "Türk Hava Yolları",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Ulaştırma",
    description: "Flag carrier airline of Türkiye.",
    descriptionTr: "Türkiye'nin bayrak taşıyıcı havayolu.",
    basePrice: 312.6,
    marketCap: 4.3e11,
    peRatio: 3.8,
    featured: true,
    sortOrder: 40,
    avgVolume: 38_000_000,
  }),
  inst({
    id: "GARAN",
    symbol: "GARAN",
    yahooSymbol: "GARAN.IS",
    name: "Garanti BBVA",
    nameTr: "Garanti BBVA",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Bankacılık",
    description: "Major private bank in Türkiye.",
    descriptionTr: "Türkiye'nin önde gelen özel bankalarından.",
    basePrice: 118.4,
    marketCap: 4.97e11,
    peRatio: 5.2,
    dividendYield: 3.1,
    featured: true,
    sortOrder: 41,
    avgVolume: 62_000_000,
  }),
  inst({
    id: "AKBNK",
    symbol: "AKBNK",
    yahooSymbol: "AKBNK.IS",
    name: "Akbank",
    nameTr: "Akbank",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Bankacılık",
    description: "Turkish commercial bank.",
    descriptionTr: "Türkiye'de faaliyet gösteren ticari banka.",
    basePrice: 62.15,
    marketCap: 3.23e11,
    peRatio: 4.9,
    sortOrder: 42,
    avgVolume: 74_000_000,
  }),
  inst({
    id: "EREGL",
    symbol: "EREGL",
    yahooSymbol: "EREGL.IS",
    name: "Ereğli Demir Çelik",
    nameTr: "Ereğli Demir Çelik",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Sanayi",
    description: "Integrated steel producer.",
    descriptionTr: "Entegre demir-çelik üreticisi.",
    basePrice: 48.72,
    marketCap: 1.7e11,
    peRatio: 8.4,
    sortOrder: 43,
    avgVolume: 55_000_000,
  }),
  inst({
    id: "BIMAS",
    symbol: "BIMAS",
    yahooSymbol: "BIMAS.IS",
    name: "BİM",
    nameTr: "BİM",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Perakende",
    description: "Hard-discount grocery retailer.",
    descriptionTr: "Sert indirim formatında gıda perakendecisi.",
    basePrice: 542.5,
    marketCap: 3.28e11,
    peRatio: 18.6,
    sortOrder: 44,
  }),
  inst({
    id: "ASELS",
    symbol: "ASELS",
    yahooSymbol: "ASELS.IS",
    name: "Aselsan",
    nameTr: "Aselsan",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Savunma",
    description: "Defense electronics company.",
    descriptionTr: "Savunma elektroniği şirketi.",
    basePrice: 78.9,
    marketCap: 3.59e11,
    peRatio: 21.3,
    sortOrder: 45,
  }),
  inst({
    id: "TUPRS",
    symbol: "TUPRS",
    yahooSymbol: "TUPRS.IS",
    name: "Tüpraş",
    nameTr: "Tüpraş",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Enerji",
    description: "Oil refining company.",
    descriptionTr: "Petrol rafineri şirketi.",
    basePrice: 164.8,
    marketCap: 3.17e11,
    peRatio: 6.1,
    sortOrder: 46,
  }),
  inst({
    id: "SISE",
    symbol: "SISE",
    yahooSymbol: "SISE.IS",
    name: "Şişecam",
    nameTr: "Şişecam",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Sanayi",
    description: "Glass and chemicals group.",
    descriptionTr: "Cam ve kimya grubu.",
    basePrice: 44.18,
    marketCap: 1.35e11,
    peRatio: 9.7,
    sortOrder: 47,
  }),
  inst({
    id: "KCHOL",
    symbol: "KCHOL",
    yahooSymbol: "KCHOL.IS",
    name: "Koç Holding",
    nameTr: "Koç Holding",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Holding",
    description: "Diversified industrial conglomerate.",
    descriptionTr: "Çeşitlendirilmiş sanayi holdingi.",
    basePrice: 186.4,
    marketCap: 4.72e11,
    peRatio: 7.2,
    sortOrder: 48,
  }),
  inst({
    id: "SAHOL",
    symbol: "SAHOL",
    yahooSymbol: "SAHOL.IS",
    name: "Sabancı Holding",
    nameTr: "Sabancı Holding",
    type: "stock",
    region: "tr",
    exchange: "BIST",
    currency: "TRY",
    sector: "Holding",
    description: "Conglomerate spanning banking, energy and retail.",
    descriptionTr: "Bankacılık, enerji ve perakende odaklı holding.",
    basePrice: 92.35,
    marketCap: 1.88e11,
    peRatio: 6.8,
    sortOrder: 49,
  }),
  inst({
    id: "SAP",
    symbol: "SAP",
    yahooSymbol: "SAP.DE",
    name: "SAP",
    nameTr: "SAP",
    type: "stock",
    region: "eu",
    exchange: "XETRA",
    currency: "EUR",
    sector: "Teknoloji",
    description: "Enterprise software company.",
    descriptionTr: "Kurumsal yazılım şirketi.",
    basePrice: 218.6,
    marketCap: 2.55e11,
    peRatio: 38.4,
    sortOrder: 50,
  }),
  inst({
    id: "MC",
    symbol: "MC",
    yahooSymbol: "MC.PA",
    name: "LVMH",
    nameTr: "LVMH",
    type: "stock",
    region: "eu",
    exchange: "EPA",
    currency: "EUR",
    sector: "Tüketici",
    description: "Luxury goods group.",
    descriptionTr: "Lüks tüketim grubu.",
    basePrice: 642.8,
    marketCap: 3.21e11,
    peRatio: 22.9,
    sortOrder: 51,
  }),
  inst({
    id: "7203",
    symbol: "7203",
    yahooSymbol: "7203.T",
    name: "Toyota",
    nameTr: "Toyota",
    type: "stock",
    region: "asia",
    exchange: "TSE",
    currency: "JPY",
    sector: "Otomotiv",
    description: "Global automotive manufacturer.",
    descriptionTr: "Küresel otomotiv üreticisi.",
    basePrice: 2684,
    marketCap: 3.52e13,
    peRatio: 9.1,
    sortOrder: 52,
  }),
  inst({
    id: "SPY",
    symbol: "SPY",
    yahooSymbol: "SPY",
    name: "SPDR S&P 500 ETF",
    nameTr: "SPDR S&P 500 ETF",
    type: "etf",
    region: "us",
    exchange: "NYSEARCA",
    currency: "USD",
    sector: "ETF",
    description: "Tracks the S&P 500 index.",
    descriptionTr: "S&P 500 endeksini takip eder.",
    basePrice: 564.2,
    sortOrder: 60,
    avgVolume: 58_000_000,
  }),
  inst({
    id: "QQQ",
    symbol: "QQQ",
    yahooSymbol: "QQQ",
    name: "Invesco QQQ",
    nameTr: "Invesco QQQ",
    type: "etf",
    region: "us",
    exchange: "NASDAQ",
    currency: "USD",
    sector: "ETF",
    description: "Tracks the Nasdaq-100.",
    descriptionTr: "Nasdaq-100 endeksini takip eder.",
    basePrice: 486.7,
    sortOrder: 61,
    avgVolume: 36_000_000,
  }),
  inst({
    id: "GLD",
    symbol: "GLD",
    yahooSymbol: "GLD",
    name: "SPDR Gold Shares",
    nameTr: "SPDR Altın",
    type: "etf",
    region: "us",
    exchange: "NYSEARCA",
    currency: "USD",
    sector: "ETF",
    description: "Physically backed gold ETF.",
    descriptionTr: "Fiziki altın karşılıklı ETF.",
    basePrice: 238.4,
    sortOrder: 62,
  }),
  inst({
    id: "EEM",
    symbol: "EEM",
    yahooSymbol: "EEM",
    name: "iShares MSCI Emerging",
    nameTr: "iShares Gelişmekte Olan",
    type: "etf",
    region: "global",
    exchange: "NYSEARCA",
    currency: "USD",
    sector: "ETF",
    description: "Emerging market equities ETF.",
    descriptionTr: "Gelişmekte olan ülke hisse ETF'si.",
    basePrice: 43.8,
    sortOrder: 63,
  }),
  inst({
    id: "USDTRY",
    symbol: "USD/TRY",
    yahooSymbol: "TRY=X",
    name: "US Dollar / Turkish Lira",
    nameTr: "Dolar / Türk Lirası",
    type: "fx",
    region: "tr",
    exchange: "FOREX",
    currency: "TRY",
    sector: "Döviz",
    description: "Spot USDTRY exchange rate.",
    descriptionTr: "USD/TRY spot döviz kuru.",
    basePrice: 34.18,
    featured: true,
    sortOrder: 70,
  }),
  inst({
    id: "EURTRY",
    symbol: "EUR/TRY",
    yahooSymbol: "EURTRY=X",
    name: "Euro / Turkish Lira",
    nameTr: "Euro / Türk Lirası",
    type: "fx",
    region: "tr",
    exchange: "FOREX",
    currency: "TRY",
    sector: "Döviz",
    description: "Spot EURTRY exchange rate.",
    descriptionTr: "EUR/TRY spot döviz kuru.",
    basePrice: 37.02,
    featured: true,
    sortOrder: 71,
  }),
  inst({
    id: "EURUSD",
    symbol: "EUR/USD",
    yahooSymbol: "EURUSD=X",
    name: "Euro / US Dollar",
    nameTr: "Euro / Dolar",
    type: "fx",
    region: "global",
    exchange: "FOREX",
    currency: "USD",
    sector: "Döviz",
    description: "Spot EURUSD exchange rate.",
    descriptionTr: "EUR/USD spot döviz kuru.",
    basePrice: 1.0834,
    featured: true,
    sortOrder: 72,
  }),
  inst({
    id: "GBPUSD",
    symbol: "GBP/USD",
    yahooSymbol: "GBPUSD=X",
    name: "Pound / US Dollar",
    nameTr: "Sterlin / Dolar",
    type: "fx",
    region: "global",
    exchange: "FOREX",
    currency: "USD",
    sector: "Döviz",
    description: "Spot GBPUSD exchange rate.",
    descriptionTr: "GBP/USD spot döviz kuru.",
    basePrice: 1.274,
    sortOrder: 73,
  }),
  inst({
    id: "USDJPY",
    symbol: "USD/JPY",
    yahooSymbol: "JPY=X",
    name: "US Dollar / Yen",
    nameTr: "Dolar / Yen",
    type: "fx",
    region: "asia",
    exchange: "FOREX",
    currency: "JPY",
    sector: "Döviz",
    description: "Spot USDJPY exchange rate.",
    descriptionTr: "USD/JPY spot döviz kuru.",
    basePrice: 149.62,
    sortOrder: 74,
  }),
  inst({
    id: "GBPTRY",
    symbol: "GBP/TRY",
    yahooSymbol: "GBPTRY=X",
    name: "Pound / Turkish Lira",
    nameTr: "Sterlin / Türk Lirası",
    type: "fx",
    region: "tr",
    exchange: "FOREX",
    currency: "TRY",
    sector: "Döviz",
    description: "Spot GBPTRY exchange rate.",
    descriptionTr: "GBP/TRY spot döviz kuru.",
    basePrice: 43.55,
    sortOrder: 75,
  }),
  inst({
    id: "BTC",
    symbol: "BTC",
    yahooSymbol: "BTC-USD",
    name: "Bitcoin",
    nameTr: "Bitcoin",
    type: "crypto",
    region: "global",
    exchange: "CRYPTO",
    currency: "USD",
    sector: "Kripto",
    description: "Largest cryptocurrency by market cap.",
    descriptionTr: "Piyasa değerine göre en büyük kripto varlık.",
    basePrice: 67420,
    marketCap: 1.33e12,
    featured: true,
    sortOrder: 80,
    avgVolume: 28_000_000_000,
  }),
  inst({
    id: "ETH",
    symbol: "ETH",
    yahooSymbol: "ETH-USD",
    name: "Ethereum",
    nameTr: "Ethereum",
    type: "crypto",
    region: "global",
    exchange: "CRYPTO",
    currency: "USD",
    sector: "Kripto",
    description: "Smart-contract blockchain network.",
    descriptionTr: "Akıllı sözleşme blokzinciri ağı.",
    basePrice: 3284,
    marketCap: 3.95e11,
    featured: true,
    sortOrder: 81,
    avgVolume: 14_000_000_000,
  }),
  inst({
    id: "SOL",
    symbol: "SOL",
    yahooSymbol: "SOL-USD",
    name: "Solana",
    nameTr: "Solana",
    type: "crypto",
    region: "global",
    exchange: "CRYPTO",
    currency: "USD",
    sector: "Kripto",
    description: "High-throughput layer-1 blockchain.",
    descriptionTr: "Yüksek işlem hacimli katman-1 blokzinciri.",
    basePrice: 148.6,
    marketCap: 7.1e10,
    sortOrder: 82,
  }),
  inst({
    id: "XRP",
    symbol: "XRP",
    yahooSymbol: "XRP-USD",
    name: "XRP",
    nameTr: "XRP",
    type: "crypto",
    region: "global",
    exchange: "CRYPTO",
    currency: "USD",
    sector: "Kripto",
    description: "Cross-border payments token.",
    descriptionTr: "Sınır ötesi ödeme token'ı.",
    basePrice: 0.584,
    marketCap: 3.3e10,
    sortOrder: 83,
  }),
  inst({
    id: "GOLD",
    symbol: "XAU",
    yahooSymbol: "GC=F",
    name: "Gold",
    nameTr: "Ons Altın",
    type: "commodity",
    region: "global",
    exchange: "COMEX",
    currency: "USD",
    sector: "Emtia",
    description: "Gold futures, USD per troy ounce.",
    descriptionTr: "Altın vadeli işlemi, ons başına USD.",
    basePrice: 2648,
    featured: true,
    sortOrder: 90,
  }),
  inst({
    id: "XAUTRY",
    symbol: "GRAMALTIN",
    yahooSymbol: "GC=F",
    name: "Gold gram TRY",
    nameTr: "Gram Altın",
    type: "commodity",
    region: "tr",
    exchange: "LOCAL",
    currency: "TRY",
    sector: "Emtia",
    description: "Indicative gram gold price in Turkish lira.",
    descriptionTr: "Gram altının Türk lirası cinsinden gösterge fiyatı.",
    basePrice: 2845,
    featured: true,
    sortOrder: 91,
  }),
  inst({
    id: "SILVER",
    symbol: "XAG",
    yahooSymbol: "SI=F",
    name: "Silver",
    nameTr: "Gümüş",
    type: "commodity",
    region: "global",
    exchange: "COMEX",
    currency: "USD",
    sector: "Emtia",
    description: "Silver futures, USD per troy ounce.",
    descriptionTr: "Gümüş vadeli işlemi, ons başına USD.",
    basePrice: 31.42,
    sortOrder: 92,
  }),
  inst({
    id: "OIL",
    symbol: "CL",
    yahooSymbol: "CL=F",
    name: "WTI Crude",
    nameTr: "Brent / WTI Petrol",
    type: "commodity",
    region: "global",
    exchange: "NYMEX",
    currency: "USD",
    sector: "Emtia",
    description: "West Texas Intermediate crude oil futures.",
    descriptionTr: "WTI ham petrol vadeli işlemi.",
    basePrice: 78.4,
    featured: true,
    sortOrder: 93,
  }),
  inst({
    id: "NATGAS",
    symbol: "NG",
    yahooSymbol: "NG=F",
    name: "Natural Gas",
    nameTr: "Doğal Gaz",
    type: "commodity",
    region: "global",
    exchange: "NYMEX",
    currency: "USD",
    sector: "Emtia",
    description: "Henry Hub natural gas futures.",
    descriptionTr: "Henry Hub doğal gaz vadeli işlemi.",
    basePrice: 2.84,
    sortOrder: 94,
  }),
];

const hoursAgo = (hours: number) => Date.now() - hours * 3_600_000;

export const NEWS_CATALOG: NewsDTO[] = [
  {
    id: "n1",
    slug: "bist-100-bankacilik-onculugunde-yukseldi",
    category: "Borsa",
    title: "BIST 100 günü yükselişle kapattı: Bankacılık hisseleri öncülük etti",
    summary:
      "Küresel risk iştahının artmasıyla yerel endeks yüzde 1,2 yükseldi. Yabancı yatırımcı işlemleri gün içinde hızlandı.",
    body: `Borsa İstanbul'da BIST 100 endeksi günü yüzde 1,2 yükselişle 9.842 puandan kapattı. Bankacılık endeksi yüzde 1,8 değer kazanırken sanayi hisselerinde daha temkinli bir seyir izlendi.

İşlem hacmi 18,4 milyar liranın üzerine çıktı. Piyasa katılımcıları, küresel tahvil faizlerindeki gevşeme ve yurt içi likidite koşullarının hisse senedi talebini desteklediğini belirtti.

Analistler kısa vadede 9.900 direncinin izleneceğini, geri çekilmelerde 9.650 desteğinin önem kazandığını ifade ediyor. Bu metin yatırım tavsiyesi değildir.`,
    author: "borsahatti Editörü",
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "XU100",
    breaking: true,
    featured: true,
    published: true,
    publishedAt: hoursAgo(0.15),
    relatedSymbols: ["XU100", "GARAN", "AKBNK"],
  },
  {
    id: "n2",
    slug: "merkez-bankasi-rezervleri-rekor",
    category: "Döviz",
    title: "Merkez Bankası rezervleri rekor seviyede: Piyasalar nasıl yorumluyor?",
    summary: "Brüt rezervlerdeki artış, döviz kurunda kısa vadeli istikrar beklentisini güçlendirdi.",
    body: `TCMB brüt rezervlerinin yeni bir zirveye ulaşması, döviz piyasasında oynaklığın azalabileceğine dair beklentileri artırdı. USD/TRY günü dar bantta tamamladı.

Ekonomistler rezerv kompozisyonunun ve swap yükümlülüklerinin de birlikte okunması gerektiğini vurguluyor. Kur tarafında 34,00-34,40 bandı kısa vadeli denge aralığı olarak izleniyor.

Haber, kamuya açık makro verilerin genel bir özetidir; döviz alım-satım önerisi içermez.`,
    author: "Ekonomi Masası",
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "USDTRY",
    breaking: false,
    featured: true,
    published: true,
    publishedAt: hoursAgo(0.4),
    relatedSymbols: ["USDTRY", "EURTRY"],
  },
  {
    id: "n3",
    slug: "gram-altinda-yeni-zirve",
    category: "Altın",
    title: "Gram altında yeni zirve: Yatırımcılar hangi seviyeleri izliyor?",
    summary: "Jeopolitik gerilim ve küresel faiz beklentileri güvenli liman talebini canlı tutuyor.",
    body: `Gram altın, ons altındaki yükseliş ve kurun yatay seyriyle birlikte yeni bir zirve denemesi yaptı. Ons altın 2.640 dolar bandında tutunurken yurt içi gram fiyatı 2.845 liraya yaklaştı.

Kıymetli metal analistleri, reel faiz görünümü değişmedikçe güvenli liman talebinin devam edebileceğini belirtiyor. 2.800 lira psikolojik destek, 2.900 lira ise ilk direnç olarak öne çıkıyor.

Emtia fiyatları hızla değişebilir; buradaki seviyeler yalnızca piyasa takibi içindir.`,
    author: "Emtia Analiz",
    imageUrl: "https://images.unsplash.com/photo-1610375229632-c7158c35a537?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "XAUTRY",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(0.7),
    relatedSymbols: ["XAUTRY", "GOLD"],
  },
  {
    id: "n4",
    slug: "bitcoin-67-bin-dolar-bandinda",
    category: "Kripto",
    title: "Bitcoin 67 bin dolar bandında: Kurumsal alımlar hız kesmiyor",
    summary: "ETF akışları ve makro veri takvimi kripto piyasasında volatiliteyi artırabilir.",
    body: `Bitcoin, 67.000 dolar civarında tutunmaya çalışırken Ethereum 3.280 dolar bandında işlem gördü. Spot ETF girişleri, kurumsal talebin sürdüğüne işaret ediyor.

Kısa vadede ABD enflasyon verisi ve faiz beklentileri kripto varlıkların yönünü belirleyebilir. Analistler 65.000 dolar desteği kırılırsa satışların hızlanabileceğini, 69.000 üzerinin ise yeni bir ralli için gerekli olduğunu söylüyor.

Kripto varlıklar yüksektir risk taşır; kayıp yaşanabilir.`,
    author: "Dijital Varlıklar",
    imageUrl: "https://images.unsplash.com/photo-1621761190629-d1438e743788?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "BTC",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(1.1),
    relatedSymbols: ["BTC", "ETH"],
  },
  {
    id: "n5",
    slug: "holding-yatirim-plani",
    category: "Şirket",
    title: "Holding şirketinden 2 milyar TL'lik yatırım planı açıklandı",
    summary: "Enerji ve teknoloji alanındaki yeni yatırımlar 2026 sonuna kadar tamamlanması hedefleniyor.",
    body: `Bir yerli holding, enerji depolama ve yazılım iştiraklerine yönelik 2 milyar liralık yatırım programı açıkladı. Planın 2026 sonuna kadar kademeli olarak hayata geçirilmesi bekleniyor.

Yönetim, yatırımların ihracat gelirlerini ve istihdamı artıracağını belirtti. Hisse tepkisi gün içinde sınırlı kaldı; yatırımcılar nakit akışı etkisini bilanço döneminde daha net görecek.

Şirket açıklamaları ileriye dönük ifadeler içerebilir ve gerçekleşmeyebilir.`,
    author: "Şirket Haberleri",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "KCHOL",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(2),
    relatedSymbols: ["KCHOL", "SAHOL"],
  },
  {
    id: "n6",
    slug: "enflasyon-verisi-oncesi-piyasalar",
    category: "Ekonomi",
    title: "Enflasyon verisi öncesi piyasalar temkinli seyrediyor",
    summary: "Analistler çekirdek enflasyonda yavaşlama sinyallerine dikkat çekiyor.",
    body: `Yurt içi enflasyon takvimi öncesinde hisse ve döviz piyasalarında işlemler sakinleşti. Tahvil faizleri sınırlı gerilerken bankacılık hisseleri görece güçlü kaldı.

Ekonomistler, çekirdek göstergelerde yavaşlama görülmesi halinde politika faizine dair beklentilerin yeniden fiyatlanabileceğini belirtiyor. Aksi bir sürpriz ise kısa vadeli kâr realizasyonunu tetikleyebilir.

Makro veriler geriye dönüktür; tek bir açıklama uzun vadeli trendi tek başına belirlemez.`,
    author: "Makro Gündem",
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "XU100",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(3),
    relatedSymbols: ["XU100", "USDTRY"],
  },
  {
    id: "n7",
    slug: "teknoloji-hisselerinde-karlilik-raporu",
    category: "Borsa",
    title: "Küresel teknoloji hisselerinde kârlılık raporu: Yapay zeka harcamaları izleniyor",
    summary: "Yatırımcılar bulut ve çip üreticilerinin sermaye harcaması rehberliğine odaklandı.",
    body: `ABD işlem gününde teknoloji hisseleri karışık bir tablo çizdi. Yatırımcılar, yapay zeka altyapısına yapılan harcamaların ne kadarının gelir artısına dönüşeceğini sorguluyor.

Çip üreticilerinde işlem hacmi ortalamanın üzerinde kaldı. Kısa vadeli fiyatlamada rehberlik revizyonları, çarpanlardan daha belirleyici hale geldi.

Sektör rotasyonu hızlı olabilir; tek hisseye yoğunlaşmak riski artırır.`,
    author: "Küresel Piyasalar",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "NVDA",
    breaking: false,
    featured: true,
    published: true,
    publishedAt: hoursAgo(4.5),
    relatedSymbols: ["NVDA", "MSFT", "AAPL"],
  },
  {
    id: "n8",
    slug: "petrol-fiyatlarinda-arz-endisesi",
    category: "Emtia",
    title: "Petrol fiyatlarında arz endişesi: WTI 78 dolar bandında",
    summary: "Stok verileri ve jeopolitik başlıklar enerji emtialarında oynaklığı artırdı.",
    body: `WTI ham petrol 78 dolar civarında dalgalandı. Piyasa, stok açıklamaları ile üretim kesintisi haberlerini aynı anda fiyatlıyor.

Enerji analistleri, talep tarafında mevsimsel yavaşlama görülürken arz kesintilerinin fiyatı desteklediğini belirtiyor. Rafineri marjları da yakından izleniyor.

Emtia kaldıraçlı ürünlerde kayıp, yatırılan tutarı aşabilir.`,
    author: "Emtia Masası",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "OIL",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(5),
    relatedSymbols: ["OIL", "TUPRS", "XOM"],
  },
  {
    id: "n9",
    slug: "thy-yolcu-trafigi-rekor",
    category: "Şirket",
    title: "THY yolcu trafiği rekor kırdı: Filo yatırımları hızlanıyor",
    summary: "Dış hat doluluk oranındaki artış, nakit akışı beklentilerini destekledi.",
    body: `Türk Hava Yolları, aylık yolcu istatistiklerinde yeni bir zirve açıkladı. Dış hat doluluk oranı yükselişini sürdürürken kargo gelirleri de güçlü kaldı.

Şirket, filoya eklenecek yeni gövdelerin birim maliyeti düşürmesini hedefliyor. Hisse, açıklama sonrası endeksin üzerinde performans gösterdi.

Operasyonel veriler ileriye dönük kârlılığı garanti etmez.`,
    author: "Ulaştırma Servisi",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "THYAO",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(6),
    relatedSymbols: ["THYAO"],
  },
  {
    id: "n10",
    slug: "avrupa-borsalari-dax-takibi",
    category: "Borsa",
    title: "Avrupa borsaları temkinli: DAX rekor denemesinde",
    summary: "Almanya sanayi siparişleri ve ECB beklentileri Avrupa hisselerini yönlendirdi.",
    body: `DAX, rekor seviyelere yakın işlem görürken FTSE 100 daha yatay bir seyir izledi. Yatırımcılar Avrupa Merkez Bankası'nın faiz patikasına dair yeni ipuçları arıyor.

İhracatçı şirketlerde kur etkisi karışık. Güçlü euro, Avrupa dışı gelirleri baskılayabilir.

Bölgesel endeksler birbirinden ayrışabilir; tek endeks tüm kıtayı temsil etmez.`,
    author: "Avrupa Masası",
    imageUrl: "https://images.unsplash.com/photo-1569025743873-ea3a9ade89f9?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "DAX",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(7),
    relatedSymbols: ["DAX", "FTSE", "SAP"],
  },
  {
    id: "n11",
    slug: "nasdaq-acilis-oncesi",
    category: "Borsa",
    title: "Nasdaq açılış öncesi: Çip ve yazılım hisseleri ayrışıyor",
    summary: "Vadeli işlemler sınırlı pozitifken yatırımcılar rehberlik diline odaklandı.",
    body: `ABD vadelileri hafif artıda. Nasdaq bileşik endeksinde yazılım hisseleri savunmacı dururken çip üreticilerinde işlemler daha hareketli.

Piyasa katılımcıları, faiz indirimi fiyatlamasının teknoloji çarpanlarını ne kadar destekleyeceğini tartışıyor.

ABD seansı, yurt içi kapanıştan sonra açıldığı için BIST üzerindeki etki gecikmeli görülebilir.`,
    author: "Wall Street Masası",
    imageUrl: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "IXIC",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(8),
    relatedSymbols: ["IXIC", "QQQ", "NVDA"],
  },
  {
    id: "n12",
    slug: "aselsan-ihracat-sozlesmesi",
    category: "Şirket",
    title: "Aselsan yeni ihracat sözleşmesi imzaladı",
    summary: "Savunma elektroniği siparişi, gelecek üç yıla yayılan teslimat takvimi içeriyor.",
    body: `Aselsan, yurt dışı bir müşteriyle çok yıllı tedarik sözleşmesi imzaladığını duyurdu. Teslimatların üç yıla yayılması bekleniyor.

Açıklamada tutar belirtilmedi. Piyasa, benzer geçmiş sözleşmelerin kârlılık katkısını referans alarak sınırlı alım yaptı.

Sözleşme iptali veya gecikme riski her zaman mevcuttur.`,
    author: "Savunma Sanayi",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80&auto=format&fit=crop",
    sourceUrl: "",
    ticker: "ASELS",
    breaking: false,
    featured: false,
    published: true,
    publishedAt: hoursAgo(9),
    relatedSymbols: ["ASELS"],
  },
];

export const VIDEO_CATALOG: VideoDTO[] = [
  {
    id: "v1",
    title: "How The Stock Exchange Works (For Dummies)",
    channel: "Kurzgesagt",
    youtubeId: "F3QpgXBtDeo",
    duration: "5:28",
    category: "Eğitim",
    featured: true,
    published: true,
    sortOrder: 1,
  },
  {
    id: "v2",
    title: "What is a Stock? How Markets Work",
    channel: "TED-Ed",
    youtubeId: "p7HKvqRI_Bo",
    duration: "4:32",
    category: "Eğitim",
    featured: true,
    published: true,
    sortOrder: 2,
  },
  {
    id: "v3",
    title: "Bonds vs Stocks — explained simply",
    channel: "Two Minute Papers / eğitim",
    youtubeId: "iq5lP3n10u4",
    duration: "8:12",
    category: "Eğitim",
    featured: false,
    published: true,
    sortOrder: 3,
  },
  {
    id: "v4",
    title: "How inflation works",
    channel: "Khan Academy",
    youtubeId: "7tbG1olY2t4",
    duration: "6:40",
    category: "Makro",
    featured: false,
    published: true,
    sortOrder: 4,
  },
];

export const DEFAULT_WATCHLIST = ["XU100", "USDTRY", "XAUTRY", "BTC", "AAPL", "THYAO", "GARAN"];

export function getInstrumentSeed(idOrSymbol: string): InstrumentSeed | undefined {
  const key = idOrSymbol.trim().toUpperCase();
  return INSTRUMENT_CATALOG.find(
    (item) =>
      item.id.toUpperCase() === key ||
      item.symbol.toUpperCase() === key ||
      item.symbol.replace("/", "").toUpperCase() === key,
  );
}

export function searchCatalog(query: string, limit = 12): InstrumentSeed[] {
  const q = query.trim().toLowerCase();
  if (!q) return INSTRUMENT_CATALOG.filter((i) => i.featured).slice(0, limit);
  return INSTRUMENT_CATALOG.filter((item) => {
    const hay = `${item.id} ${item.symbol} ${item.name} ${item.nameTr} ${item.yahooSymbol} ${item.sector}`.toLowerCase();
    return hay.includes(q);
  }).slice(0, limit);
}
