-- Seed: roles and role permissions. Idempotent.

INSERT OR IGNORE INTO roles (id, name, description, created_at) VALUES
  ('super_admin', 'Admin',                 'Full CRM access including role assignment and system settings', unixepoch() * 1000),
  ('admin',       'Head',                  'Manages all CRM teams and team leaders',                        unixepoch() * 1000),
  ('operator',    'Retention Team Leader', 'Manages the retention team',                                     unixepoch() * 1000),
  ('viewer',      'Sale Team Leader',      'Manages the sales team',                                         unixepoch() * 1000),
  ('retention',   'Retention',             'CRM retention employee',                                         unixepoch() * 1000),
  ('sale',        'Sale',                  'CRM sales employee',                                             unixepoch() * 1000),
  ('user',        'Client',                'Client account with read-only CRM access',                       unixepoch() * 1000);

INSERT OR IGNORE INTO permissions (role_id, permission) VALUES
  -- super_admin
  ('super_admin', 'admin.access'),
  ('super_admin', 'admin.panel'),
  ('super_admin', 'stats.view'),
  ('super_admin', 'map.live_view'),
  ('super_admin', 'sessions.view'),
  ('super_admin', 'sessions.manage'),
  ('super_admin', 'users.view'),
  ('super_admin', 'users.create'),
  ('super_admin', 'users.manage'),
  ('super_admin', 'roles.assign'),
  ('super_admin', 'audit.view'),
  ('super_admin', 'customers.manage'),
  ('super_admin', 'tickets.manage'),
  ('super_admin', 'documents.manage'),
  ('super_admin', 'reports.view'),
  ('super_admin', 'settings.manage'),
  -- head
  ('admin', 'admin.access'),
  ('admin', 'admin.panel'),
  ('admin', 'stats.view'),
  ('admin', 'map.live_view'),
  ('admin', 'sessions.view'),
  ('admin', 'sessions.manage'),
  ('admin', 'users.view'),
  ('admin', 'users.create'),
  ('admin', 'users.manage'),
  ('admin', 'roles.assign'),
  ('admin', 'audit.view'),
  ('admin', 'customers.manage'),
  ('admin', 'tickets.manage'),
  ('admin', 'documents.manage'),
  ('admin', 'reports.view'),
  -- retention team leader
  ('operator', 'admin.access'),
  ('operator', 'stats.view'),
  ('operator', 'map.live_view'),
  ('operator', 'sessions.view'),
  ('operator', 'sessions.manage'),
  ('operator', 'users.view'),
  ('operator', 'users.create'),
  ('operator', 'users.manage'),
  ('operator', 'roles.assign'),
  ('operator', 'customers.manage'),
  ('operator', 'tickets.manage'),
  ('operator', 'documents.manage'),
  ('operator', 'reports.view'),
  -- sale team leader
  ('viewer', 'admin.access'),
  ('viewer', 'stats.view'),
  ('viewer', 'map.live_view'),
  ('viewer', 'sessions.view'),
  ('viewer', 'users.view'),
  ('viewer', 'users.create'),
  ('viewer', 'users.manage'),
  ('viewer', 'roles.assign'),
  ('viewer', 'customers.manage'),
  ('viewer', 'tickets.manage'),
  ('viewer', 'reports.view'),
  -- retention
  ('retention', 'customers.manage'),
  ('retention', 'tickets.manage'),
  ('retention', 'documents.manage'),
  -- sale
  ('sale', 'customers.manage'),
  ('sale', 'tickets.manage'),
  -- client
  ('user', 'customers.manage');
