import type { FeaturedSeed } from "./types";

export const FEATURED_SEEDS: FeaturedSeed[] = [
  {
    key: "claude-4-sonnet",
    name: "Claude 4 Sonnet",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: null,
    candidates: ["claude-sonnet-4-0", "claude-sonnet-4-20250514", "claude-sonnet-4-5"],
    description: {
      tr: "Dengeli Claude 4 sohbet ve yazım modeli.",
      en: "Balanced Claude 4 model for everyday chat and writing.",
    },
  },
  {
    key: "claude-4-sonnet-1m",
    name: "Claude 4 Sonnet 1M",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: null,
    maxContext: 1_000_000,
    candidates: ["claude-sonnet-4-0", "claude-sonnet-4-5", "claude-sonnet-4-6"],
    description: {
      tr: "Uzun belgeler için 1M bağlamlı Claude 4 Sonnet.",
      en: "Claude 4 Sonnet with a 1M long-context window.",
    },
  },
  {
    key: "claude-4.5-haiku",
    name: "Claude 4.5 Haiku",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: null,
    candidates: ["claude-haiku-4-5", "claude-haiku-4-5-20251001"],
    description: {
      tr: "Hızlı ve ekonomik Claude 4.5.",
      en: "Fast, economical Claude 4.5.",
    },
  },
  {
    key: "claude-4.5-opus",
    name: "Claude 4.5 Opus",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: 200_000,
    candidates: ["claude-opus-4-5", "claude-opus-4-5-20251101"],
    description: {
      tr: "Derin muhakeme için Claude 4.5 Opus.",
      en: "Deep-reasoning Claude 4.5 Opus.",
    },
  },
  {
    key: "claude-4.5-sonnet",
    name: "Claude 4.5 Sonnet",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["claude-sonnet-4-5", "claude-sonnet-4-5-20250929"],
    description: {
      tr: "Günlük işler ve kod için Claude 4.5 Sonnet.",
      en: "Everyday work and coding with Claude 4.5 Sonnet.",
    },
  },
  {
    key: "claude-4.6-opus",
    name: "Claude 4.6 Opus",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["claude-opus-4-6"],
    description: {
      tr: "Gelişmiş Claude 4.6 Opus.",
      en: "Advanced Claude 4.6 Opus.",
    },
  },
  {
    key: "claude-4.6-sonnet",
    name: "Claude 4.6 Sonnet",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["claude-sonnet-4-6"],
    description: {
      tr: "Güncel Claude 4.6 Sonnet.",
      en: "Current Claude 4.6 Sonnet.",
    },
  },
  {
    key: "claude-4.7-opus",
    name: "Claude 4.7 Opus",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 300_000,
    maxContext: 1_000_000,
    candidates: ["claude-opus-4-7"],
    description: {
      tr: "Yüksek kapasiteli Claude 4.7 Opus.",
      en: "High-capacity Claude 4.7 Opus.",
    },
  },
  {
    key: "claude-fable-5",
    name: "Claude Fable 5",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 300_000,
    maxContext: 1_000_000,
    candidates: ["claude-fable-5"],
    description: {
      tr: "Yaratıcı ve uzun bağlamlı Fable 5.",
      en: "Creative long-context Fable 5.",
    },
  },
  {
    key: "claude-fable-5.1",
    name: "Claude Fable 5.1",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 300_000,
    maxContext: 1_000_000,
    candidates: ["claude-fable-5-1"],
    description: {
      tr: "En yeni Fable nesli.",
      en: "Latest Fable generation.",
    },
  },
  {
    key: "claude-opus-4.7-fast",
    name: "Claude Opus 4.7 (fast mode)",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["claude-opus-4-7"],
    fast: true,
    description: {
      tr: "Opus 4.7 hızlı yanıt modu.",
      en: "Opus 4.7 in fast-response mode.",
    },
  },
  {
    key: "claude-opus-4.8",
    name: "Claude Opus 4.8",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 300_000,
    maxContext: 1_000_000,
    candidates: ["claude-opus-4-8"],
    description: {
      tr: "En yeni Opus 4.8.",
      en: "Latest Opus 4.8.",
    },
  },
  {
    key: "claude-opus-5",
    name: "Claude Opus 5",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 300_000,
    maxContext: 1_000_000,
    candidates: ["claude-opus-5"],
    description: {
      tr: "Anthropic'in amiral gemisi Opus 5.",
      en: "Anthropic flagship Opus 5.",
    },
  },
  {
    key: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    vendor: "anthropic",
    vendorLabel: "Anthropic",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["claude-sonnet-5"],
    description: {
      tr: "Yeni nesil Claude Sonnet 5.",
      en: "Next-generation Claude Sonnet 5.",
    },
  },
  {
    key: "composer-1",
    name: "Composer 1",
    vendor: "cursor",
    vendorLabel: "Cursor",
    standardContext: 200_000,
    maxContext: null,
    candidates: ["cursor/composer-1", "composer-1"],
    kind: "code",
    description: {
      tr: "Cursor Composer 1 — havuza düşünce canlı katalogda görünür görünmez bağlanır.",
      en: "Cursor Composer 1 — wired the moment it appears in the live catalog.",
    },
  },
  {
    key: "composer-2.5",
    name: "Composer 2.5",
    vendor: "cursor",
    vendorLabel: "Cursor",
    standardContext: 200_000,
    maxContext: null,
    candidates: ["cursor/composer-2.5", "composer-2.5"],
    kind: "code",
    description: {
      tr: "Cursor Composer 2.5 ajan / kod modeli.",
      en: "Cursor Composer 2.5 agent / coding model.",
    },
  },
  {
    key: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-2.5-flash"],
    description: {
      tr: "Hızlı Gemini 2.5.",
      en: "Fast Gemini 2.5.",
    },
  },
  {
    key: "gemini-3-flash",
    name: "Gemini 3 Flash",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3-flash-preview", "gemini-3-flash"],
    description: {
      tr: "Gemini 3 Flash — düşük gecikme.",
      en: "Gemini 3 Flash — low latency.",
    },
  },
  {
    key: "gemini-3-pro",
    name: "Gemini 3 Pro",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3-pro", "gemini-3.1-pro-preview"],
    description: {
      tr: "Güçlü Gemini 3 Pro ailesi.",
      en: "Capable Gemini 3 Pro family.",
    },
  },
  {
    key: "gemini-3-pro-image",
    name: "Gemini 3 Pro Image Preview",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3-pro-image", "gemini-3-pro-image-preview"],
    kind: "image",
    description: {
      tr: "Metinden görsel üreten Gemini 3 Pro.",
      en: "Gemini 3 Pro text-to-image.",
    },
  },
  {
    key: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3.1-pro-preview", "gemini-3.1-pro"],
    description: {
      tr: "Güncel Gemini 3.1 Pro.",
      en: "Current Gemini 3.1 Pro.",
    },
  },
  {
    key: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3.5-flash"],
    description: {
      tr: "Gemini 3.5 Flash.",
      en: "Gemini 3.5 Flash.",
    },
  },
  {
    key: "gemini-3.6-flash",
    name: "Gemini 3.6 Flash",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3.6-flash"],
    description: {
      tr: "Gemini 3.6 Flash.",
      en: "Gemini 3.6 Flash.",
    },
  },
  {
    key: "gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3.7-flash"],
    description: {
      tr: "Gemini 3.7 Flash.",
      en: "Gemini 3.7 Flash.",
    },
  },
  {
    key: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash",
    vendor: "google",
    vendorLabel: "Google",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["gemini-3.8-flash"],
    description: {
      tr: "En yeni Gemini Flash.",
      en: "Latest Gemini Flash.",
    },
  },
  {
    key: "glm-5.2",
    name: "GLM 5.2",
    vendor: "zai",
    vendorLabel: "Z.ai",
    standardContext: 200_000,
    maxContext: null,
    candidates: ["z-ai/glm-5.2", "glm-5.2"],
    description: {
      tr: "Z.ai GLM 5.2.",
      en: "Z.ai GLM 5.2.",
    },
  },
  {
    key: "gpt-5",
    name: "GPT-5",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5"],
    description: {
      tr: "OpenAI GPT-5.",
      en: "OpenAI GPT-5.",
    },
  },
  {
    key: "gpt-5-fast",
    name: "GPT-5 Fast",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5"],
    fast: true,
    description: {
      tr: "GPT-5 hızlı yanıt profili.",
      en: "GPT-5 fast-response profile.",
    },
  },
  {
    key: "gpt-5-mini",
    name: "GPT-5 Mini",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5-mini"],
    description: {
      tr: "Hafif GPT-5 Mini.",
      en: "Lightweight GPT-5 Mini.",
    },
  },
  {
    key: "gpt-5-codex",
    name: "GPT-5-Codex",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5-codex", "gpt-5.3-codex"],
    kind: "code",
    description: {
      tr: "Kod odaklı GPT-5 Codex.",
      en: "Code-focused GPT-5 Codex.",
    },
  },
  {
    key: "gpt-5.1-codex",
    name: "GPT-5.1 Codex",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.1-codex", "gpt-5.3-codex"],
    kind: "code",
    description: {
      tr: "GPT-5.1 Codex.",
      en: "GPT-5.1 Codex.",
    },
  },
  {
    key: "gpt-5.1-codex-max",
    name: "GPT-5.1 Codex Max",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.1-codex-max", "gpt-5.3-codex"],
    kind: "code",
    description: {
      tr: "Daha geniş Codex Max.",
      en: "Larger Codex Max.",
    },
  },
  {
    key: "gpt-5.1-codex-mini",
    name: "GPT-5.1 Codex Mini",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.1-codex-mini", "gpt-5.3-codex"],
    kind: "code",
    description: {
      tr: "Hızlı Codex Mini.",
      en: "Fast Codex Mini.",
    },
  },
  {
    key: "gpt-5.2",
    name: "GPT-5.2",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.2"],
    description: {
      tr: "GPT-5.2.",
      en: "GPT-5.2.",
    },
  },
  {
    key: "gpt-5.2-codex",
    name: "GPT-5.2 Codex",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.2-codex", "gpt-5.3-codex"],
    kind: "code",
    description: {
      tr: "GPT-5.2 Codex.",
      en: "GPT-5.2 Codex.",
    },
  },
  {
    key: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.3-codex"],
    kind: "code",
    description: {
      tr: "GPT-5.3 Codex.",
      en: "GPT-5.3 Codex.",
    },
  },
  {
    key: "gpt-5.4",
    name: "GPT-5.4",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: 1_000_000,
    candidates: ["gpt-5.4"],
    description: {
      tr: "GPT-5.4 — 1M bağlama kadar.",
      en: "GPT-5.4 — up to 1M context.",
    },
  },
  {
    key: "gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.4-mini"],
    description: {
      tr: "GPT-5.4 Mini.",
      en: "GPT-5.4 Mini.",
    },
  },
  {
    key: "gpt-5.4-nano",
    name: "GPT-5.4 Nano",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: null,
    candidates: ["gpt-5.4-nano"],
    description: {
      tr: "En hafif GPT-5.4.",
      en: "Smallest GPT-5.4.",
    },
  },
  {
    key: "gpt-5.5",
    name: "GPT-5.5",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: 1_000_000,
    candidates: ["gpt-5.5"],
    description: {
      tr: "GPT-5.5.",
      en: "GPT-5.5.",
    },
  },
  {
    key: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: 1_000_000,
    candidates: ["gpt-5.6-luna"],
    description: {
      tr: "GPT-5.6 Luna — hızlı hat.",
      en: "GPT-5.6 Luna — fast lane.",
    },
  },
  {
    key: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: 1_000_000,
    candidates: ["gpt-5.6-sol"],
    description: {
      tr: "GPT-5.6 Sol — muhakeme hattı.",
      en: "GPT-5.6 Sol — reasoning lane.",
    },
  },
  {
    key: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    vendor: "openai",
    vendorLabel: "OpenAI",
    standardContext: 272_000,
    maxContext: 1_000_000,
    candidates: ["gpt-5.6-terra"],
    description: {
      tr: "GPT-5.6 Terra — dengeli hat.",
      en: "GPT-5.6 Terra — balanced lane.",
    },
  },
  {
    key: "grok-4.5",
    name: "Grok 4.5",
    vendor: "xai",
    vendorLabel: "xAI",
    standardContext: 256_000,
    maxContext: null,
    candidates: ["x-ai/grok-4.5", "grok-4.5"],
    description: {
      tr: "xAI Grok 4.5.",
      en: "xAI Grok 4.5.",
    },
  },
  {
    key: "grok-4.6",
    name: "Grok 4.6",
    vendor: "xai",
    vendorLabel: "xAI",
    standardContext: 256_000,
    maxContext: null,
    candidates: ["x-ai/grok-4.6", "grok-4.6"],
    description: {
      tr: "xAI Grok 4.6.",
      en: "xAI Grok 4.6.",
    },
  },
  {
    key: "kimi-k2.7-code",
    name: "Kimi K2.7 Code",
    vendor: "moonshot",
    vendorLabel: "Moonshot",
    standardContext: 262_000,
    maxContext: null,
    candidates: ["moonshotai/kimi-k2.7-code", "kimi-k2.7-code"],
    kind: "code",
    description: {
      tr: "Moonshot Kimi K2.7 Code.",
      en: "Moonshot Kimi K2.7 Code.",
    },
  },
  {
    key: "kimi-k3",
    name: "Kimi K3",
    vendor: "moonshot",
    vendorLabel: "Moonshot",
    standardContext: 200_000,
    maxContext: 1_000_000,
    candidates: ["moonshotai/kimi-k3", "kimi-k3"],
    description: {
      tr: "Moonshot Kimi K3.",
      en: "Moonshot Kimi K3.",
    },
  },
  {
    key: "muse-spark-1.3",
    name: "Muse Spark 1.3",
    vendor: "meta",
    vendorLabel: "Meta",
    standardContext: 300_000,
    maxContext: 1_000_000,
    candidates: ["meta/muse-spark-1.3", "muse-spark-1.3", "meta/muse-glimmer-30b"],
    description: {
      tr: "Meta Muse Spark 1.3 — katalogda yoksa en yakın Muse modeline bağlanır.",
      en: "Meta Muse Spark 1.3 — falls back to the closest live Muse model.",
    },
  },
];
